### Site metadata ###

site_name: Storytools Documentation
site_description: Documenations for Storytools Blender addon
site_author: 'Samuel Bernou'
site_url: https://pullusb.github.io/storytools-docs
repo_url: https://github.com/Pullusb/storytools-docs
edit_uri: edit/main/docs
docs_dir: docs/

### Build settings ###

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Tutorial:
      - Installation: tutorial/installation.md
      - Project Setup : tutorial/setup-project.md
      - Sidebar Panels : tutorial/sidebar-panels.md
      - Control Bar : tutorial/story-toolbar.md
      - Tool Presets : tutorial/tool-presets.md
      - Shot Management : tutorial/shot-management.md
      - Resources: tutorial/resources.md
  - About Storytools: about-storytools.md
